### PR TITLE
Added extended authentication

### PR DESCRIPTION
**Pull request by Bannsaenger**
Added extended authentication. The existing "Simple" authentication is still working.
If user is empty the authentication type wil be set to "None" with the first start of the instance config.
Question:
I added the translations to the words.js
Wich is the right way to do the translation. words.js or the i.18n folder,
or could it be transferred automatically ?
Thanks.

### CODE REVIEW

**Comment by Apollon77** [comment]
I think if doing that way we should at least store the passwords encrypted because they are unencrypted in the instance object ...
for this you need to get the secret and then define own methods like in https://github.com/Apollon77/ioBroker.meross/blob/master/admin/index_m.html#L34-L56 and use them in admin page ... ad a comparable decrypt in the adapter logic.

The automatic encrypt/decrypt will not work here because it is "not static fieldnames"

**Comment by Bannsaenger** [comment]
The passwords are ready encryted for node-red. I think it's save enough because the passwords reside in the settings.js from node red the same way.

**Comment by Apollon77** [comment]
ahah now you say it I see it ... good

**Comment by Apollon77** [comment]
PR looks good ... ready to merge when you are :-)

**Comment by Bannsaenger** [comment]
When you do the words to i18n then im finished yet.

**Comment by Apollon77** [comment]
kk, thx!! wil merge as soon as we verified another topic

**Comment by Apollon77** [comment]
@Bannsaenger Please have a last look https://github.com/ioBroker/ioBroker.node-red/commit/4d579f1bf8fc401233c194220f94a773accf7fad

I also added the fallback logic to main.js

**Comment by Bannsaenger** [comment]
That makes sense, Thanks

**Pull request merged**
