### PR TITLE
Add possibility to get object instead of state

### LINKED ISSUE #28: iobroker get node for state object
Hi,

Would it be possible to introduce a new node (or maybe upgrade the existing "get" one) to read out informations about an object (not the state)?

For example I'm trying to set the color of different lights where for some lights hue is 0-360 while others have hue 0-65535. I set the topic at the beginning of my flow and would like to use a function in the end to convert the input payload to the correct format depending on the topic. ioBroker provides a common.min and common.max property but I don't see a way to use that from within node-red.

Maybe a dropdown in the iobroker get node where you can choose between "state" and "object" and then a switch in: https://github.com/ioBroker/ioBroker.node-red/blob/master/nodes/ioBroker.js#L361
to use getForeignObject instead of getForeignState would be enough for that...

### PR DESCRIPTION
**Pull request by WolfspiritM**
This adds the possibility to not only get the state but also get the object.
It allows for example getting the max value for a light to convert percentage to the correct value

Fixes #28

I've been using this for a long time like that without issues and reimplemented it from version to version and now I thought it might be better to create a PR.

It would be great if someone can test it as I remember that old nodes might have problems with new settings.

### CODE REVIEW

**Comment by Apollon77** [comment]
Would it not be cleaner (and also prevents the five problem) to create new nodes like an GetObject node?

**Comment by WolfspiritM** [comment]
@Apollon77 I changed it so it's using a new "ioBroker get object" node :smile:

**Comment by Apollon77** [comment]
Thank you. I will check tomorrow.

**Comment by Apollon77** [comment]
published as 1.3.0 to npm/latest

**Pull request merged**
