### PR TITLE
Allow custom theme, fixed scoped packages

### PR DESCRIPTION
**Pull request by klein0r**
- https://github.com/ioBroker/ioBroker.node-red/issues/425

### CODE REVIEW

**Comment by holomekc** [comment]
thx for adding the theme config!!!

**Comment by Apollon77** [comment]
@klein0r Thank you! Ready for release? Minor increase?

**Comment by klein0r** [comment]
@Apollon77 Yes, please release a new minor version

**Comment by Apollon77** [comment]
on it's way

**Pull request merged**
