### PR TITLE
Replace HTTP Basic Authentication by Node-RED Login Page

### PR DESCRIPTION
**Pull request by jwiesel**
Hi @GermanBluefox , @Apollon77,
given the issues #98 , #58 I thought I'd give my first PR for this repository a try.

## Implemented changes
* replaced setting `httpAdminAuth` by `adminAuth` in file settings.js
* Adapted setting replacement code in file main.js
* Changed password hashing from MD5 to bcrypt.js in file index_m.html
* Added bcrypt.min.js and linked it in index_m.html

Implementation based on Security guidance by Node-RED: https://nodered.org/docs/user-guide/runtime/securing-node-red#usernamepassword-based-authentication

## Testing done so far
* I did various tests by installing the adapter into ioBroker from my Github fork (`npm install https://github.com/jwiesel/ioBroker.node-red/tarball/master`) as indicated in the ioBroker documentation: https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/adapterdev.md#deploying
 
## Test Instructions
* Install the adapter in your ioBroker installation
* Set or replace your password in the Node-RED instance settings. - Important: As you might still have an MD5 based password stored, that has to be replaced by the bcrypt based password. After saving the settings, wait a few seconds until Node-RED is up and running again
* Open node-red --> now the node-red "login page" should load instead of the HTTP Basic Authentication popup. Login with your newly set username + password
* Logout out of Node-RED again
* Go to the instance settings and remove username + password. Wait a few seconds until Node-RED is up and running again
* Open node-red / F5 to reload the page again. Now you should directly see your flows without the need to login

## Observations
* The bcrypt algorithm seems to need a bit longer than expected by ioBroker during save operation of the instance settings. I sometimes get a message after clicking on "Save", that I have unsaved changes which I might lose, when leaving the page. I always click on OK and it is saved anyhow. Maybe someone has an idea to to avoid the popup

## Further improvement suggestions
* If you agree to merge this PR, I could remove the MD5 code beforehand from index_m.html to avoid unused overhead code.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you!
I think it is not backward compatible, it should be mentioned in readme.

**Comment by Apollon77** [comment]
... and we shoud make it a major version increase

**Comment by jwiesel** [comment]
Thanks for taking the PR into account :-)
I fully agree to the readme entry. Users who already have authentication enabled will have to enter their password again after the upgrade.
Regarding the major release you might want to consider another feature I have been working on to enable HTTPS in Node-RED based on the ioBroker certificates. I'll create the PR in a few minutes.

**Comment by jwiesel** [comment]
just added PR #103

**Comment by Apollon77** [comment]
I started to check some other fixes and update node-red, idea is that we have a more clean "baselin" before bringing this in and do a major version bump

**Comment by jwiesel** [comment]
perfectly fine for me. Comparing apples and oranges only makes it more difficult.

**Comment by Apollon77** [comment]
I hink we now can go ahead. Could you please resolve the conflixt? Then I would merge it and we put it into form for tests or such

**Comment by jwiesel** [comment]
Hi @Apollon77 , I just resolved the conflict. You can merge the PR now. Thanks!

**Comment by GermanBluefox** [comment]
What is the status now? @Apollon77

**Comment by Apollon77** [comment]
I was very busy with the js-controlelr 3.0 release the last weeks, but starting to catch up now with all these open topics, sorry

**Comment by jwiesel** [comment]
Thank you guys! Happy to be part of version 2.0.0 :-)

**Pull request merged**
